### ISSUE TITLE
Feat:  colorful registration form

### ISSUE THREAD

**Issue by Sagar-Mondal** [harshmittal1750/hacktoberfest-2023#6]
### What feature?

I want to add html and css file for colorful registration form made by me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sagar-Mondal** [comment]
@harshmittal1750 Kindly assign me this issue. Thank you.

**Comment by harshmittal1750** [comment]
You can start working on it.
All the best.
